// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcS85DcAEm1ZYYXGYdqez8Wcdp7OtWZdI',
    appId: '1:348113485162:web:7cc17738233668c5abf913',
    messagingSenderId: '348113485162',
    projectId: 'test-1-8b0e5',
    authDomain: 'test-1-8b0e5.firebaseapp.com',
    storageBucket: 'test-1-8b0e5.appspot.com',
    measurementId: 'G-F306WJF3M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzzbwLTGuPg9DHttlV0NtP5EWcJjH0-qk',
    appId: '1:348113485162:android:d917deb0fa882815abf913',
    messagingSenderId: '348113485162',
    projectId: 'test-1-8b0e5',
    storageBucket: 'test-1-8b0e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoRhC6jxtl4JW6JHfkk7KxnvPrcJ4n4po',
    appId: '1:348113485162:ios:f511cd250179df50abf913',
    messagingSenderId: '348113485162',
    projectId: 'test-1-8b0e5',
    storageBucket: 'test-1-8b0e5.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoRhC6jxtl4JW6JHfkk7KxnvPrcJ4n4po',
    appId: '1:348113485162:ios:c892443f345f2c51abf913',
    messagingSenderId: '348113485162',
    projectId: 'test-1-8b0e5',
    storageBucket: 'test-1-8b0e5.appspot.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
