// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd71hJQSpJSsJ1Rn0KRdhjOkR1kZ12pto',
    appId: '1:283327849519:web:7ff9eb6ddadc09c89712da',
    messagingSenderId: '283327849519',
    projectId: 'fir-notification-project-62293',
    authDomain: 'fir-notification-project-62293.firebaseapp.com',
    storageBucket: 'fir-notification-project-62293.appspot.com',
    measurementId: 'G-B0TF25448H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvvUO53sE7nR0yHCm2axbA39-gVMgBUv8',
    appId: '1:283327849519:android:0f6bfd1db6de692a9712da',
    messagingSenderId: '283327849519',
    projectId: 'fir-notification-project-62293',
    storageBucket: 'fir-notification-project-62293.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA_U4dfcfv2TZRyjYWacEFabvJ3Q4oCzA',
    appId: '1:283327849519:ios:c086764efb7c964e9712da',
    messagingSenderId: '283327849519',
    projectId: 'fir-notification-project-62293',
    storageBucket: 'fir-notification-project-62293.appspot.com',
    iosBundleId: 'com.example.firebaseNotificationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA_U4dfcfv2TZRyjYWacEFabvJ3Q4oCzA',
    appId: '1:283327849519:ios:44615eac487dfa119712da',
    messagingSenderId: '283327849519',
    projectId: 'fir-notification-project-62293',
    storageBucket: 'fir-notification-project-62293.appspot.com',
    iosBundleId: 'com.example.firebaseNotificationProject.RunnerTests',
  );
}
